### ISSUE TITLE
[bug] Items Randomly Deleted (Possible Mod Interaction?)

### ISSUE THREAD

**Issue by GalacticRuler** [robclancy/valheim-bigger-chests#1]
With this mod installed, we've noticed a lot of random things in random slots of any chest disappear. All clients and the server have this mod, yet this still occurs.

We also are all running:
Crafting With Containers
Simple Recycling
Anti Slip Shoes
Bigger Boat Map Explore Radius
Bigger Pickup Radius
Build Camera
First Person Camera Mod
Crafting Station Level Range
Equipment And Quick Slots
Explore Together
Faster Teleportation
Fermenter Percentage
Floating Items
Hold Attack
item Stacks
Jam
Loot Multiplier
Minimal Status Effects
Multicraft
No Rain Damage
Not So Needy Crafting Station
PreWorkout
Locator
Skip Intro
Show Plant Progress
Softcore Death
Torches Eternal
Triple Bronze
Unrestricted Portals
Use Equipment In Water
Drop That + its Boss Metals addon
Sell That
Brawler

**Comment by robclancy** [comment]
The only time I have been able to reproduce items being deleted is when someone without the mod moves something in a chest causing an update without the extra slots. I just checked bug reports for another mod that does the same thing as this and they don't seem to have issues unless someone doesn't have the mod installed.

It's hard to fix without being able to easily reproduce it. Tomorrow I will look into it some more. If there is a way I can just make the server control the state then it should solve everything and even allow non mod users to work.

**Comment by robclancy** [comment]
I wonder if item stacks could be an issue somehow.

**Comment by GalacticRuler** [comment]
I think it's actually the Crafting With Chests mod, maybe
it reports items used in the console and constantly shows resources being used but "used 0" and then things vanish.

and yeah it's 100% random slots, everywhere.

**Comment by VirtueAvatar** [comment]
This bug is not a mod conflict, this is a bug in Crafting With Containers 1.0.8 and is fixed in 1.0.9.
