### ISSUE TITLE
Black metal chest bug

### ISSUE THREAD

**Issue by BioHazardN7** [robclancy/valheim-bigger-chests#4]
After updating the game to the Hearth & Home with a new chest, there was a problem - it decreased.
[Black Metal Chest with Valheim Bigger Chests addon](https://i.ibb.co/KVVRHMW/Black-Metal-Chest-Bug.png)
[Black Metal Chest without Valheim Bigger Chests addon](https://i.ibb.co/mXRCcHW/Black-Metal-Chest-Normal.png)

**Comment by robclancy** [comment]
Okay updated everywhere. I don't change the size of this new chest because it is basically max size.
